// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGbmmSnlIPe5T9D6Hw7kESG0236OmlPsE',
    appId: '1:392428631464:web:fbc8664b8f050cd862199d',
    messagingSenderId: '392428631464',
    projectId: 'loyalty-card-storage-app-2a98d',
    authDomain: 'loyalty-card-storage-app-2a98d.firebaseapp.com',
    storageBucket: 'loyalty-card-storage-app-2a98d.firebasestorage.app',
    measurementId: 'G-D9W5LGRS68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo-ixaWNx-3_Up18qs_5d_MKAv8n8BsGQ',
    appId: '1:392428631464:android:5c0c986dae78ff8962199d',
    messagingSenderId: '392428631464',
    projectId: 'loyalty-card-storage-app-2a98d',
    storageBucket: 'loyalty-card-storage-app-2a98d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMKJaLWNubwn98SEYWVnFnEp8qbySlXOE',
    appId: '1:392428631464:ios:0e0e05b3ee596f8b62199d',
    messagingSenderId: '392428631464',
    projectId: 'loyalty-card-storage-app-2a98d',
    storageBucket: 'loyalty-card-storage-app-2a98d.firebasestorage.app',
    iosBundleId: 'com.example.flutterBasedLloyaltyCardStorageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMKJaLWNubwn98SEYWVnFnEp8qbySlXOE',
    appId: '1:392428631464:ios:0e0e05b3ee596f8b62199d',
    messagingSenderId: '392428631464',
    projectId: 'loyalty-card-storage-app-2a98d',
    storageBucket: 'loyalty-card-storage-app-2a98d.firebasestorage.app',
    iosBundleId: 'com.example.flutterBasedLloyaltyCardStorageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGbmmSnlIPe5T9D6Hw7kESG0236OmlPsE',
    appId: '1:392428631464:web:5ec66f4dc03f080562199d',
    messagingSenderId: '392428631464',
    projectId: 'loyalty-card-storage-app-2a98d',
    authDomain: 'loyalty-card-storage-app-2a98d.firebaseapp.com',
    storageBucket: 'loyalty-card-storage-app-2a98d.firebasestorage.app',
    measurementId: 'G-DCY8B36PVT',
  );

}